{% set version = "0.1.4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-coranking
  version: {{ version|replace("-", "_") }}

source:
  fn: coRanking_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/coRanking_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/coRanking/coRanking_{{ version }}.tar.gz
  sha256: 7a601871e331a0a626cf44e66844ff86f15f449453d5eb7c1878ac2c53f09b0f

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win32]

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rtsne
    - r-scatterplot3d

  run:
    - r-base
    - r-rtsne
    - r-scatterplot3d

test:
  commands:
    - $R -e "library('coRanking')"  # [not win]
    - "\"%R%\" -e \"library('coRanking')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=coRanking
  license: GPL-3
  summary: Calculates the co-ranking matrix to assess the quality of a dimensionality reduction.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
