{% set version = "0.2.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-coranking
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/coRanking_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/coRanking/coRanking_{{ version }}.tar.gz
  sha256: 8b8a361f25ebf3c4bced4ca9233b723b1104fad06c9bca914124b7830b002bb0

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('coRanking')"           # [not win]
    - "\"%R%\" -e \"library('coRanking')\""  # [win]

about:
  home: https://github.com/gdkrmr/coRanking
  license: GPL-3.0-only
  summary: Calculates the co-ranking matrix to assess the quality of a dimensionality reduction.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: coRanking
# Title: Co-Ranking Matrix
# Version: 0.1.4
# Author: Guido Kraemer
# Maintainer: Guido Kraemer <gkraemer@bgc-jena.mpg.de>
# Description: Calculates the co-ranking matrix to assess the quality of a dimensionality reduction.
# URL: https://github.com/gdkrmr/coRanking
# BugReports: https://github.com/gdkrmr/coRanking/issues
# License: GPL-3 | file LICENSE
# Imports: methods, graphics, stats
# RoxygenNote: 6.1.0
# Collate: 'coranking-package.R' 'coranking.R' 'coranking_internals.R' 'lcmc.R' 'criteria.R' 'image.R' 'rankmatrix.R' 'submatrix.R'
# Suggests: testthat, knitr, rmarkdown, Rtsne, scatterplot3d
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2018-10-01 11:34:16 UTC; gkraemer
# Repository: CRAN
# Date/Publication: 2018-10-01 12:20:03 UTC
