travis:
  secure:
    BINSTAR_TOKEN: suryuF3UnJPznYcGc7ZQjuLZZH6VAPcMhvJjmu1eauxl7591YVBDgYSmY9tyWvRvbbjSDYjecgP8E5mYERBI7wwhB1aBslK4F1SCqW5puJqDC9Ck/Oe9Cvw/7ulROs2hlL9yK1+rLroKBORDzLncZpZ+QUiPuNQW9a3Y0CnrM/J2z88l8D340nvNP+3Km3yQxYgMaXBNqWev42pA55JJkMy+HOxiexhyI186x55lHwtrG3ONyRg51cYbYyccMqRbbpwZS7ZGF/SGEC5Vnrf0h79/pxiUHWiQpZFujFBRK/ZUmtZqzCZJ/iSqOiJ0uhiXHkJabtSdco/gcif12dPFyZraZnH1fc3OEGC2ZtWW6PQwb5cByZIIACMgxyaFY2BvNMZNlwADKKLbO/5Cm+yWpBldXtos8wKEnwF87UvJHORbi+iuJ0SFM7utsQFHOHqFsjinklT8bXhK/87mn26qzKA2i8bqpu9ofqxfQXIrFaqiaY+FPUz05JmRyDPZLK5MUcSO6PQOqPdd+OdJibWycH8LDWn72NsqD/iOIKKmjRPuy+X5NP68Dq3FaSjhikEeSNCSQfT6wjjQ75k/mqxcLf6/jiSiT0LPfkVZa+731NpRR0n5b3nNKZTVfz/0KT0R8xHlTdBfy29Y+dxqh8G0XccdpW4020wt5txyjdR2zxA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
