travis:
  secure:
    BINSTAR_TOKEN: 0rfGKg+q7Go3Mlr5piHPMVO9bS8X1j7PAAG3H3ZOsyGkCrpdx5+DTw5T8blNvBmHD520iLAxch+8d22kXG0vdJQWTuo+/0TarnpL46TmxkRyfqgyrFwSxI0dW1d3fMDoWC9hNZQwhVJs5IaQ6asalpkfQ9xvRWG6hwmJLrt0Ocjq4ZV1eND1YGH0pM0dCBN30GZoM+6i0AvEP4Koemz+V+cE8X2VN19C+fDzaVqyFK9J8XXyOMKHCsvKOKzZu6Y9k542kXbkoViyruvUXV+0KRFPn1VjkTzCTb2dzPxFrM7LAKRkwjwuO4cnpH+oJVKvJTHtZgSR90X/KYo7iIX/mQ8msHa13JtLWXPmkNyukIt1mhUNOuRRJVZaLaUHDg6uh0OFIfyXi2q+7RKFWIMU/XwmBSwhEoZxX4NWqbun8ld6Bf+MtaVPTlnAticnvtn+EkTrHJFFpzMNTbED0o6vW2tDaY584rscSRfN8F+XgQGK6Parpsjp2B9YzLtlEIQDQBn5utgY7IpLGlvm6ep9x4A55e2YZOKomX31PAE9nlek/BX176DyO5cL3vUPW81HhX0DxTiiEu9H7K+t4NnM/YazsH1jgeES00MqNdEntoxjx1gDThgORV7fCYEoPYjSW8dc/i9hbU1WJY5oFpRrZGaHyZVFN51r7hJLoo2PePs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
