travis:
  secure:
    BINSTAR_TOKEN: wqyXnL+g1Ph/2S88WNHJYYxnDbubi83PRlSr1JmOZtht/gUos6tfjcDJL9Y0Sbvj172nUARuy5UYyjLUedKToTebFa7u1WI436gO2syzu+nc0TnaKIJk2wlygb9AcG2DVQb1Blc6lUvXaC5fRKj/WAiQouOP2t7goengUuQk2pNYviWX1y88aJGiMT5XN9+J+eXtA1e/a+WSlPm6ld4ogHRHTWt7Ub425e/sWVPf491jH1EGkIL0gdMdsFyno+PNAaPZIUzHXyGkZxbbKI5lOUVZaEDX8ULJvwCoijYak5WiGiqsSpdzVDkBbWM5aL+YJseP8ivefBr4adopgO07It/u4wDKIE9MFXiziLKKgmAIp0RQRtE4MQh/r5FT6uwAR1rERWz65i7ziaTjAh2a95esIBfyegvC8yDlAcguCY8OlyaJUBgh3WUJj8HA4oebNAPbhspP+sBsaP2F2PEaEzKFH2iIF5q4RzAUZJDLyBNyRgV4IDa1lPuYb1JFZ3q2xm7clwDrbtydr+HP63fFRJbSWe7uRChrjus7DZfOJCjlXDjhaDbHYC4n2ByA+2YbMcy2YJqpxDSQQdafD6wNQPw86epsYd8ewZ9npud0Bn4ZPsnFX0+sAZOx1ffXX6K1GKj1vOqVYT/M6OFEVzBpoTvtMcy8jI5qA+J140Dtjlg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
