appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Zg6u88CwuvzOyZMfGOOUClQu5/xMzOO8ay0fsCg/rjwikUYdhffi7rpYH+SFg8+JuvIeG146e74PvV0OEpDZr8jGFJdAlokSAj0K16SS1hSUUnVHmqQ+napamqYaDBgkOIhuVAy5jWRJWx0hBcUB3lghjbfJYsmlXIM+EMjIKHja15IILm+UJNni5aP5oEARTevJaqFmf5Ikepxd1MBl5wylVZfN/IcTk5amLAfcROS36OG1YSOkZJMR3Cng12+jY66C0jbQ/vK9Ss3mO62bP9y5Vk3jSVoeO1wHEGdbB23CKOQj2KX6ZiuS+DHbZho4nvEmsK3CuTU3sGXoNXIJe81GBYX7aElzun8GAdpz1bc/+/48SLz4UOuu6PQOYGM6RXsHIycCJNubUAHXErDF58IKawqwf3hybjarmqWyi016ohNmnIzJavmb/O9bEKjZfCMJ7+TABdzMvyWJyif0FmnNf5M/KkWTK4MI/cp50RU2sk1FPJeAxFhx6SK5ROfmh9izgSVeDapvDpYwAU5E42InKRXjRk4loEHjeYxp2c3/YqpGCWKO0a5gWkK4De6BwoA0wTTZV2d/vCpSMtQhuTiFNF4PvumXhV3izaTbcjMVKUIH+95Sk/aq2fhnXWfnOb8rPjKc0SQymzNQyLnojUK5HZ9gPKatgHR0K6UDVj8=}
