travis:
  secure:
    BINSTAR_TOKEN: bP2CBM/cXVUOvCjDUVY/CgEE6fyW+YAAQyNnqKnXGyG510kEpnIBF66vshbDb9pSYxJpONu8kWuRxDMLMaAO2H/8zxIlgvTLdNvrxOdzEuXUbjoo6Kar7U2e/q1QJ4FI9sRw4NnBjjfAlEEvn+DH1Y1VFCQNEni88UxKvaG4/P5Sho/bRKZyxAi09pFIgT2PC8YoPYwajzmcyw4ooRUD0LnNCrZeFrUU072pBdNqMJ10VuPBg5+sCMcRpdzWCwVKFvm69FshK3noiT1WrY7Dt1ysMB45pw/7TYSUVwpeZT1CsSkRkbQUU9d2MiO4PL3Nd4KnQBSELTIL/Wl7CIm4/JS4u+nCci1IjmC6Ss9GMBudixHEX1hGN52nnM6HMvUWZv8/KJ85HYD3QLWGCO8jZZ2YafY5EqDPQgl8Dk7s9gH9/3s8rLwkRCm3MTtJBo3qTUD2Nh79yLht66KP0plB75AKLqbUW+qwp5yukhDtJWiFE4zSqERisxNvbyqyZiOsH/TPcBRNZhm3LrsuwhEZo3t5eZRAA2DM8Igjv4j3Ago5vUAq4FmUsrABGhGYACImzMDer9Of7KEgKkuHDzc7phDKO+SC+P5MF3XaAHC4xlbVcJ6R6tpID46M9A5KGL8W4gG4NHdNA5ww3NP1l0g0sZDLe4+EotpRcTWmoA343Fg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
